#!/bin/bash

#######################################################################################################################
#
# To construct maximum likelihood trees for MAGs, the bacterial and archaeal concatenated marker gene alignments 
# generated by GTDB-Tk were used as input for IQ-TREE v2.1.2. The best-fit model was determined using ModelFinder 
# with the -m flag. The models used to generate trees for bacteria and archaea MAGs were Q.pfam + R10 and LG + F + R3,
# respectively. Instructions on how to install and run GTDB-TK can be found at http://www.iqtree.org/
#
#######################################################################################################################

source ~/anaconda3/bin/activate iqtree

#create tree for dereplicated bacteria MAGs
iqtree -s MAG_GTDBTKalign/gtdbtk.bac120.user_msa.fasta -m MFP -T 24 --prefix MAG_bact_iqtree


#create tree for dereplicated archaea MAGs
iqtree -s MAG_GTDBTKalign/gtdbtk.ar122.user_msa.fasta -m MFP -T 24 --prefix MAG_arch_iqtree

conda deactivate